### ISSUE TITLE
Basic Example: Uncaught TypeError: this._timeline.groupsData._data is undefined

### ISSUE THREAD

**Issue by studiospring** [javdome/timeline-arrows#2]
Your [basic example](https://javdome.github.io/timeline-arrows/examples/basic_example.html) is not showing any arrows and is throwing:
Uncaught TypeError: this._timeline.groupsData._data is undefined.

I'm trying this on Firefox 81. When I try in Chromium 86, the arrows do not show, but I get a different error:
Uncaught TypeError: Cannot read property 'get' of undefined
Your "group example" has similar issues!

**Comment by javdome** [comment]
Hi!!, I have updated the repo and it is working again.

In version 7.3.11 of vis-timeline, there have been changes that broke the library... but now it is fixed again.
