### ISSUE TITLE
When both items are not visible, the arrows are hidden

### ISSUE THREAD

**Issue by Bengya** [javdome/timeline-arrows#8]
Demo video:
https://screenapp.io/app/#/shared/530b09db-03ff-4338-a2e8-4df988efcdb0
The arrow between "Item 3" and "Item 5" disappears, once both items are out of the visible area. Is there a way to overcome this problem and make it easier to follow the arrow lines in case of distant items (both horizontally and vertically)?

In the original issue, there are 2 comments where the example makes it possible:
https://github.com/almende/vis/issues/1699#issuecomment-407963710
and
https://github.com/almende/vis/issues/1699#issuecomment-499297577

**Comment by javdome** [comment]
Hi!!, I have just release a new version. Check version **v4.6.0**
I have added a new option _hideWhenItemsNotVisible_. Try setting this option to `false` (see Readme).
You can see the output in the new example:
https://javdome.github.io/timeline-arrows/examples/hideWhenItemsNotVisible_Option.html

Regards!!
